name: CLIPS
favicon: null
layout_spectrum: 0.2963322480209172
typography_spectrum: 0.7661540869157761
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8282505094539374
  lightness: 0.7723348012659699
  saturation: 0.9002259962726384
  rhythmicContrast: 0.9861735522281379
purpose: []
